version: '3.5'
services:
  payment:
    container_name: 'payment'
    restart: on-failure
    build: .
    volumes:
      - .:/usr/src/payment
      - /usr/src/payment/node_modules
      - /home/was/TeleditClient/install/bin:/user/src/TeleditClient
    command: >
      sh -c "npm install && npm run start:dev"
    ports:
      - '${M_PORT}:${PORT}'

networks:
  default:
    name: '${NETWORK_NAME}'
